version: "3.9"

services:
  backend: 
    build: ./server
    ports:
      - "5000:5000"
    container_name: backend_service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/react-app
      target: development
    ports:
      - "5173:5173"
    container_name: frontend_service
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
